# This manifest holds the information the app needs to run on the Nextmv Cloud.
type: python
runtime: ghcr.io/nextmv-io/runtime/python:3.11
python:
  # All listed packages will get bundled with the app.
  pip-requirements: requirements.txt

# List all files/directories that should be included in the app. Globbing
# (e.g.: configs/*.json) is supported.
files:
  - main.py
  - visuals.py

configuration:
  options:
    strict: false
    validation:
      enforce: none
    items:
      - name: objective
        option_type: string
        default: "average_distance"
        required: false
        description: "minimizes for average_distance, total_distance, or max_distance"
        additional_attributes:
          values:
            - "average_distance"
            - "total_distance"
            - "max_distance"
        ui:
          control_type: select
          hidden_from:
            - operator