version: "2"
run:
  go: "1.21"
linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomodguard_v2
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    dupl:
      threshold: 200
    gocyclo:
      min-complexity: 12
    lll:
      line-length: 120
    tagliatelle:
      case:
        rules:
          json: snake
        use-field-name: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocyclo
          - nestif
        path: shift-scheduling/main\.go
      - linters:
          - lll
          - unparam
        path: shift-scheduling/schema\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
