[project]
name = "community-apps"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "ruff>=0.15.12",
]

[tool.ruff]
target-version = "py312"

# Ignore specific directories
exclude = [
    "python-gurobi-price-optimization",
    "python-wf-databricks/hello-world-nextmv-app.ipynb",
    "python-wf-databricks-ml-gurobi-price-optimization/avocado-price-optimizer.ipynb",
    "python-wf-databricks-ml-gurobi-price-optimization/avocado-ml-regressor.ipynb",
]

# Rule configuration.
line-length = 120

# Rule selection.
[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP",  # pyupgrade
]

# Allow generous cyclomatic complexity for examples.
[tool.ruff.lint.mccabe]
max-complexity = 25

[tool.ruff.lint.per-file-ignores]
# Set a different max complexity for a specific file
"python-ortools-shiftassignment/main.py" = ["C901"]
"python-gurobi-knapsack/main.ipynb" = ["I001"]
"python-highs-knapsack/main.ipynb" = ["I001"]
"python-nextroute/main.ipynb" = ["I001"]
