# This manifest holds the information the app needs to run on the Nextmv Cloud.
type: python
runtime: ghcr.io/nextmv-io/runtime/python:3.11
# List all files/directories that should be included in the app. Globbing
# (e.g.: configs/*.json) is supported.
files:
  - main.py
python:
  # Packages the app depends on need to be listed in a requirements.txt file
  # that is referenced here. All listed packages will get bundled with the app.
  pip-requirements: requirements.txt

configuration:
  # Specify the format the app reads and writes.
  content:
    format: json
  # Define the options (parameters) of the app.
  options:
    strict: false
    items:
      - name: duration
        option_type: int
        default: 30
        description: Max runtime duration (in seconds).
        required: false
      - name: provider
        option_type: string
        default: SCIP
        description: Solver provider.
        required: false
      - name: factor-maximize-weekly-hours-per-worker
        option_type: float
        default: 0.0
        description: Weight to apply for maximizing total weekly hours per worker (up to allowed maximum).
        required: false
      - name: factor-balance-total-hours
        option_type: float
        default: 0.0
        description: Weight to apply for balancing worker hours.
        required: false
      - name: factor-maximize-preferences
        option_type: float
        default: 1.0
        description: Weight to apply for total preference matches.
        required: false
