apps:
  - name: cpp-hello-world
    scripts:
      - name: 0.sh
        skip: true
      - name: 1.sh
        skip: true
      - name: 2.sh
        skip: true
      - name: 3.sh
        skip: true
  - name: cs-sardinecan-packing
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        stderr: true
      - name: 3.sh
        skip: true
      - name: 4.sh
        skip: true
      - name: 5.sh
        skip: true
      - name: 6.sh
        skip: true
      - name: 7.sh
        skip: true
  - name: go-highs-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
  - name: go-highs-orderfulfillment
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
  - name: go-highs-shiftscheduling
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
  - name: go-nextroute
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
  - name: java-hello-world
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: java-gurobi-knapsack
    scripts:
      - name: 0.sh
        silent: true
      # We cannot run Java Gurobi without a license, so we skip these tests.
      - name: 1.sh
        skip: true
      - name: 2.sh
        skip: true
      - name: 3.sh
        skip: true
  - name: java-gurobi-multiknapsack-multiexcel
    scripts:
      - name: 0.sh
        silent: true
      # We cannot run Java Gurobi without a license, so we skip these tests.
      - name: 1.sh
        skip: true
      - name: 2.sh
        skip: true
      - name: 3.sh
        skip: true
      - name: 4.sh
        skip: true
  - name: java-hexaly-knapsack
    scripts:
      # Without the license and no maven package, we cannot run the tests.
      - name: 0.sh
        skip: true
      - name: 1.sh
        skip: true
      - name: 2.sh
        skip: true
      - name: 3.sh
        skip: true
  - name: java-ortools-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: java-ortools-routing
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ampl-facilitylocation
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ampl-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ampl-priceoptimization
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-cplex-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-cuopt-routing
    scripts:
      - name: 0.sh
        skip: true
  - name: python-gams-cutstock
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
  - name: python-gamspy-traveling-salesman
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
  - name: python-gurobi-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-hello-world
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-hexaly-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
      - name: 2.sh
        skip: true
  - name: python-hexaly-generic
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
      - name: 2.sh
        skip: true
      - name: 3.sh
        skip: true
      - name: 4.sh
        skip: true
      - name: 5.sh
        skip: true
  - name: python-highs-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
      - name: 2.sh
        skip: true
  - name: python-nextmv-gurobipy-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-nextroute
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        silent: true
  - name: python-ortools-costflow
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
      - name: 2.sh
        skip: true
  - name: python-ortools-demandforecasting
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
      - name: 2.sh
        skip: true
  - name: python-ortools-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
      - name: 2.sh
        skip: true
  - name: python-ortools-knapsack-multicsv
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ortools-multiknapsack-multiexcel
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
  - name: python-ortools-region-allocation
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
      - name: 2.sh
        skip: true
  - name: python-ortools-routing
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
      - name: 2.sh
        skip: true
  - name: python-ortools-shiftassignment
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
      - name: 2.sh
        skip: true
  - name: python-ortools-shiftplanning
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
      - name: 2.sh
        skip: true
  - name: python-pyomo-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
      - name: 2.sh
        skip: true
  - name: python-pyomo-shiftassignment
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
      - name: 2.sh
        skip: true
  - name: python-pyomo-shiftplanning
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
      - name: 2.sh
        skip: true
  - name: python-pyoptinterface-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
      - name: 2.sh
        skip: true
  - name: python-pyvroom-routing
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-scip-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        stderr: true
  - name: python-tr-ortools-region-allocation
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-vroom-premium-api-routing
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
  - name: python-xpress-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-wf-custom-visuals
    scripts:
      - name: 0.sh
        skip: true
      - name: 1.sh
        skip: true
  - name: python-wf-databricks
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
      - name: 2.sh
        skip: true
  - name: python-wf-databricks-ml-gurobi-price-optimization
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
      - name: 2.sh
        skip: true
  - name: python-wf-ortools-region-allocation
    scripts:
      - name: 1.sh
        skip: true
      - name: 3.sh
        skip: true
      - name: 4.sh
        skip: true
      - name: 5.sh
        skip: true
      - name: 6.sh
        skip: true
  - name: rust-goodlp-knapsack
    scripts:
      - name: 0.sh
        skip: true
      - name: 2.sh
        skip: true
  - name: rust-hello-world
    scripts:
      - name: 1.sh
        skip: true
