apps:
  - name: go-highs-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
  - name: go-highs-orderfulfillment
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
  - name: go-highs-shiftscheduling
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
  - name: go-nextroute
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        skip: true
  - name: java-hello-world
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: java-ortools-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: java-ortools-routing
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ampl-facilitylocation
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ampl-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ampl-priceoptimization
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-gurobi-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-hello-world
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-hexaly-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
      - name: 1.sh
        skip: true
  - name: python-highs-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-nextroute
    scripts:
      - name: 0.sh
        silent: true
  - name: python-ortools-costflow
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ortools-demandforecasting
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ortools-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ortools-knapsack-multicsv
    scripts:
      - name: 0.sh
        silent: true
      - name: 1.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ortools-routing
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ortools-shiftassignment
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-ortools-shiftplanning
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-pyomo-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-pyomo-shiftassignment
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-pyomo-shiftplanning
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-pyoptinterface-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-pyvroom-routing
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
  - name: python-xpress-knapsack
    scripts:
      - name: 0.sh
        silent: true
      - name: 2.sh
        skip: true
