# This manifest holds the information the app needs to run on the Nextmv Cloud.
type: python
runtime: ghcr.io/nextmv-io/runtime/python:3.11

# We offer a few different runtimes with pre-installed packages.
# Use these for convenience, if they suit your needs.
#
# For OR-Tools, use the following runtime:
# runtime: ghcr.io/nextmv-io/runtime/ortools:latest
# For Pyomo, a use the following runtime:
# runtime: ghcr.io/nextmv-io/runtime/pyomo:latest
# For AMPL, use the following runtime:
# runtime: ghcr.io/nextmv-io/runtime/ampl:latest
# For Gurobi, use the following runtime and add the licence file 'gurobi.lic' to the files list:
# runtime: ghcr.io/nextmv-io/runtime/gurobi:latest

python:
  # Packages the app depends on need to be listed in a requirements.txt file
  # that is referenced here. All listed packages will get bundled with the app.
  pip-requirements: requirements.txt

# List all files/directories that should be included in the app. Globbing
# (e.g.: configs/*.json) is supported.
files:
  - main.py
