# This manifest holds the information the app needs to run on the Nextmv Cloud.
type: go
runtime: ghcr.io/nextmv-io/runtime/default:latest

# Directives to build a Go binary from the app.
build:
  command: go build -o main .
  environment:
    GOOS: linux
    GOARCH: arm64

# List all files/directories that should be included in the app. Globbing
# (e.g.: configs/*.json) is supported.
files:
  - main

configuration:
  options:
    strict: false
    validation:
      enforce: all
    items:
      # Check options
      - name: check.duration
        option_type: string
        default: "30s"
        description: Maximum duration of the check (env CHECK_DURATION)
        ui:
          control_type: input
          display_name: Check Duration
      - name: check.verbosity
        option_type: string
        default: "off"
        description: "{off, low, medium, high} verbosity of the check (env CHECK_VERBOSITY)"
        additional_attributes:
          values:
            - "off"
            - "low"
            - "medium"
            - "high"
        ui:
          control_type: select
          display_name: Check Verbosity

      # Format options
      - name: format.disable.progression
        option_type: bool
        default: false
        description: Disable the progression series (env FORMAT_DISABLE_PROGRESSION)
        ui:
          control_type: toggle
          display_name: Disable Progression
          hidden_from:
            - viewer
            - operator

      # Model constraint disable options
      - name: model.constraints.disable.attributes
        option_type: bool
        default: false
        description: Ignore the compatibility attributes constraint (env MODEL_CONSTRAINTS_DISABLE_ATTRIBUTES)
        ui:
          control_type: toggle
          display_name: Disable Attributes Constraint
      - name: model.constraints.disable.capacities
        option_type: string
        default: ""
        description: Ignore the capacity constraint for the given resource names (env MODEL_CONSTRAINTS_DISABLE_CAPACITIES)
        ui:
          control_type: input
          display_name: Disable Specific Capacities
      - name: model.constraints.disable.capacity
        option_type: bool
        default: false
        description: Ignore the capacity constraint for all resources (env MODEL_CONSTRAINTS_DISABLE_CAPACITY)
        ui:
          control_type: toggle
          display_name: Disable All Capacity Constraints
      - name: model.constraints.disable.distancelimit
        option_type: bool
        default: false
        description: Ignore the distance limit constraint (env MODEL_CONSTRAINTS_DISABLE_DISTANCE_LIMIT)
        ui:
          control_type: toggle
          display_name: Disable Distance Limit
      - name: model.constraints.disable.groups
        option_type: bool
        default: false
        description: Ignore the groups constraint (env MODEL_CONSTRAINTS_DISABLE_GROUPS)
        ui:
          control_type: toggle
          display_name: Disable Groups Constraint
      - name: model.constraints.disable.maximumduration
        option_type: bool
        default: false
        description: Ignore the maximum duration constraint (env MODEL_CONSTRAINTS_DISABLE_MAXIMUM_DURATION)
        ui:
          control_type: toggle
          display_name: Disable Maximum Duration
      - name: model.constraints.disable.maximumstops
        option_type: bool
        default: false
        description: Ignore the maximum stops constraint (env MODEL_CONSTRAINTS_DISABLE_MAXIMUM_STOPS)
        ui:
          control_type: toggle
          display_name: Disable Maximum Stops
      - name: model.constraints.disable.maximumwaitstop
        option_type: bool
        default: false
        description: Ignore the maximum stop wait constraint (env MODEL_CONSTRAINTS_DISABLE_MAXIMUM_WAIT_STOP)
        ui:
          control_type: toggle
          display_name: Disable Maximum Wait Stop
      - name: model.constraints.disable.maximumwaitvehicle
        option_type: bool
        default: false
        description: Ignore the maximum vehicle wait constraint (env MODEL_CONSTRAINTS_DISABLE_MAXIMUM_WAIT_VEHICLE)
        ui:
          control_type: toggle
          display_name: Disable Maximum Wait Vehicle
      - name: model.constraints.disable.mixingitems
        option_type: bool
        default: false
        description: Ignore the do not mix items constraint (env MODEL_CONSTRAINTS_DISABLE_MIXING_ITEMS)
        ui:
          control_type: toggle
          display_name: Disable Mixing Items
      - name: model.constraints.disable.precedence
        option_type: bool
        default: false
        description: Ignore the precedence (pickups & deliveries) constraint (env MODEL_CONSTRAINTS_DISABLE_PRECEDENCE)
        ui:
          control_type: toggle
          display_name: Disable Precedence
      - name: model.constraints.disable.starttimewindows
        option_type: bool
        default: false
        description: Ignore the start time windows constraint (env MODEL_CONSTRAINTS_DISABLE_START_TIME_WINDOWS)
        ui:
          control_type: toggle
          display_name: Disable Start Time Windows
      - name: model.constraints.disable.vehicleendtime
        option_type: bool
        default: false
        description: Ignore the vehicle end time constraint (env MODEL_CONSTRAINTS_DISABLE_VEHICLE_END_TIME)
        ui:
          control_type: toggle
          display_name: Disable Vehicle End Time
      - name: model.constraints.disable.vehiclestarttime
        option_type: bool
        default: false
        description: Ignore the vehicle start time constraint (env MODEL_CONSTRAINTS_DISABLE_VEHICLE_START_TIME)
        ui:
          control_type: toggle
          display_name: Disable Vehicle Start Time

      # Model constraint enable options
      - name: model.constraints.enable.cluster
        option_type: bool
        default: false
        description: Enable the cluster constraint (env MODEL_CONSTRAINTS_ENABLE_CLUSTER)
        ui:
          control_type: toggle
          display_name: Enable Cluster Constraint

      # Model objectives
      - name: model.objectives.capacities
        option_type: string
        default: ""
        description: "Capacity objective, provide triple for each resource 'name:default;factor:1.0;offset;0.0' (env MODEL_OBJECTIVES_CAPACITIES)"
        ui:
          control_type: input
          display_name: Capacities Objective
      - name: model.objectives.cluster
        option_type: float
        default: 0.0
        description: Factor to weigh the cluster objective (env MODEL_OBJECTIVES_CLUSTER)
        ui:
          control_type: input
          display_name: Cluster Objective
      - name: model.objectives.distance
        option_type: float
        default: 0.0
        description: Factor to weigh the travel distance objective (env MODEL_OBJECTIVES_DISTANCE)
        ui:
          control_type: input
          display_name: Distance Objective
      - name: model.objectives.earlyarrivalpenalty
        option_type: float
        default: 1.0
        description: Factor to weigh the early arrival objective (env MODEL_OBJECTIVES_EARLY_ARRIVAL_PENALTY)
        ui:
          control_type: input
          display_name: Early Arrival Penalty
      - name: model.objectives.latearrivalpenalty
        option_type: float
        default: 1.0
        description: Factor to weigh the late arrival objective (env MODEL_OBJECTIVES_LATE_ARRIVAL_PENALTY)
        ui:
          control_type: input
          display_name: Late Arrival Penalty
      - name: model.objectives.minstops
        option_type: float
        default: 1.0
        description: Factor to weigh the min stops objective (env MODEL_OBJECTIVES_MIN_STOPS)
        ui:
          control_type: input
          display_name: Min Stops Objective
      - name: model.objectives.stopbalance
        option_type: float
        default: 0.0
        description: Factor to weigh the stop balance objective (env MODEL_OBJECTIVES_STOP_BALANCE)
        ui:
          control_type: input
          display_name: Stop Balance Objective
      - name: model.objectives.travelduration
        option_type: float
        default: 0.0
        description: Factor to weigh the travel duration objective (env MODEL_OBJECTIVES_TRAVEL_DURATION)
        ui:
          control_type: input
          display_name: Travel Duration Objective
      - name: model.objectives.unplannedpenalty
        option_type: float
        default: 1.0
        description: Factor to weigh the unplanned objective (env MODEL_OBJECTIVES_UNPLANNED_PENALTY)
        ui:
          control_type: input
          display_name: Unplanned Penalty
      - name: model.objectives.vehicleactivationpenalty
        option_type: float
        default: 1.5
        description: Factor to weigh the vehicle activation objective (env MODEL_OBJECTIVES_VEHICLE_ACTIVATION_PENALTY)
        ui:
          control_type: input
          display_name: Vehicle Activation Penalty
      - name: model.objectives.vehiclesduration
        option_type: float
        default: 1.0
        description: Factor to weigh the vehicles duration objective (env MODEL_OBJECTIVES_VEHICLES_DURATION)
        ui:
          control_type: input
          display_name: Vehicles Duration Objective

      # Model properties
      - name: model.properties.disable.durationgroups
        option_type: bool
        default: false
        description: Ignore the durations groups of stops (env MODEL_PROPERTIES_DISABLE_DURATION_GROUPS)
        ui:
          control_type: toggle
          display_name: Disable Duration Groups
      - name: model.properties.disable.durations
        option_type: bool
        default: false
        description: Ignore the durations of stops (env MODEL_PROPERTIES_DISABLE_DURATIONS)
        ui:
          control_type: toggle
          display_name: Disable Durations
      - name: model.properties.disable.initialsolution
        option_type: bool
        default: false
        description: Ignore the initial solution (env MODEL_PROPERTIES_DISABLE_INITIAL_SOLUTION)
        ui:
          control_type: toggle
          display_name: Disable Initial Solution
      - name: model.properties.disable.stopdurationmultipliers
        option_type: bool
        default: false
        description: Ignore the stop duration multipliers defined on vehicles (env MODEL_PROPERTIES_DISABLE_STOP_DURATION_MULTIPLIERS)
        ui:
          control_type: toggle
          display_name: Disable Stop Duration Multipliers
      - name: model.properties.maximumtimehorizon
        option_type: int
        default: 15552000
        description: Maximum time horizon for the model in seconds (env MODEL_PROPERTIES_MAXIMUM_TIME_HORIZON)
        ui:
          control_type: input
          display_name: Maximum Time Horizon
          hidden_from:
            - viewer
            - operator

      # Model validation
      - name: model.validate.disable.resources
        option_type: bool
        default: false
        description: Disable the resources validation (env MODEL_VALIDATE_DISABLE_RESOURCES)
        ui:
          control_type: toggle
          display_name: Disable Resources Validation
          hidden_from:
            - viewer
            - operator
      - name: model.validate.disable.starttime
        option_type: bool
        default: false
        description: Disable the start time validation (env MODEL_VALIDATE_DISABLE_START_TIME)
        ui:
          control_type: toggle
          display_name: Disable Start Time Validation
          hidden_from:
            - viewer
            - operator
      - name: model.validate.enable.matrix
        option_type: bool
        default: false
        description: Enable matrix validation (env MODEL_VALIDATE_ENABLE_MATRIX)
        ui:
          control_type: toggle
          display_name: Enable Matrix Validation
          hidden_from:
            - viewer
            - operator
      - name: model.validate.enable.matrixasymmetrytolerance
        option_type: int
        default: 20
        description: Percentage of acceptable matrix asymmetry, requires matrix validation enabled (env MODEL_VALIDATE_ENABLE_MATRIX_ASYMMETRY_TOLERANCE)
        ui:
          control_type: input
          display_name: Matrix Asymmetry Tolerance
          hidden_from:
            - viewer
            - operator

      # Runner options
      - name: runner.input.path
        option_type: string
        default: ""
        description: The input file path (env RUNNER_INPUT_PATH)
        ui:
          control_type: input
          display_name: Input Path
          hidden_from:
            - viewer
            - operator
      - name: runner.output.path
        option_type: string
        default: ""
        description: The output file path (env RUNNER_OUTPUT_PATH)
        ui:
          control_type: input
          display_name: Output Path
          hidden_from:
            - viewer
            - operator
      - name: runner.output.solutions
        option_type: string
        default: "last"
        description: "{all, last} (env RUNNER_OUTPUT_SOLUTIONS)"
        additional_attributes:
          values:
            - "all"
            - "last"
        ui:
          control_type: select
          display_name: Output Solutions
          hidden_from:
            - viewer
            - operator
      - name: runner.profile.cpu
        option_type: string
        default: ""
        description: The CPU profile file path (env RUNNER_PROFILE_CPU)
        ui:
          control_type: input
          display_name: CPU Profile Path
          hidden_from:
            - viewer
            - operator
      - name: runner.profile.memory
        option_type: string
        default: ""
        description: The memory profile file path (env RUNNER_PROFILE_MEMORY)
        ui:
          control_type: input
          display_name: Memory Profile Path
          hidden_from:
            - viewer
            - operator

      # Solve options
      - name: solve.duration
        option_type: string
        default: "5s"
        description: Maximum duration of the solver (env SOLVE_DURATION)
        ui:
          control_type: input
          display_name: Solve Duration
      - name: solve.iterations
        option_type: int
        default: -1
        description: Maximum number of iterations, -1 assumes no limit; iterations are counted after start solutions are generated (env SOLVE_ITERATIONS)
        ui:
          control_type: input
          display_name: Solve Iterations
          hidden_from:
            - viewer
            - operator
      - name: solve.parallelruns
        option_type: int
        default: -1
        description: Maximum number of parallel runs, -1 results in using all available resources (env SOLVE_PARALLEL_RUNS)
        ui:
          control_type: input
          display_name: Parallel Runs
          hidden_from:
            - viewer
            - operator
      - name: solve.plateau.absolutethreshold
        option_type: float
        default: -1.0
        description: Absolute threshold for significant improvement (env SOLVE_PLATEAU_ABSOLUTE_THRESHOLD)
        ui:
          control_type: input
          display_name: Plateau Absolute Threshold
      - name: solve.plateau.delay
        option_type: string
        default: ""
        description: Delay before plateau detection starts (env SOLVE_PLATEAU_DELAY)
        ui:
          control_type: input
          display_name: Plateau Delay
      - name: solve.plateau.duration
        option_type: string
        default: ""
        description: Maximum duration without (significant) improvement (env SOLVE_PLATEAU_DURATION)
        ui:
          control_type: input
          display_name: Plateau Duration
      - name: solve.plateau.iterations
        option_type: int
        default: 0
        description: Maximum number of iterations without (significant) improvement (env SOLVE_PLATEAU_ITERATIONS)
        ui:
          control_type: input
          display_name: Plateau Iterations
      - name: solve.plateau.relativethreshold
        option_type: float
        default: 0.0
        description: Relative threshold for significant improvement (env SOLVE_PLATEAU_RELATIVE_THRESHOLD)
        ui:
          control_type: input
          display_name: Plateau Relative Threshold
      - name: solve.rundeterministically
        option_type: bool
        default: false
        description: Run the parallel solver deterministically (env SOLVE_RUN_DETERMINISTICALLY)
        ui:
          control_type: toggle
          display_name: Run Deterministically
          hidden_from:
            - viewer
            - operator
      - name: solve.startsolutions
        option_type: int
        default: -1
        description: Number of solutions to generate on top of those passed in; one solution generated with sweep algorithm, the rest generated randomly (env SOLVE_START_SOLUTIONS)
        ui:
          control_type: input
          display_name: Start Solutions
          hidden_from:
            - viewer
            - operator

  # Specify the format the app reads and writes.
  content:
    format: "json" # Read JSON from stdin and write JSON to stdout.
