# This manifest holds the information the app needs to run on the Nextmv Cloud.
type: python
runtime: ghcr.io/nextmv-io/runtime/python:3.11
python:
  # All listed packages will get bundled with the app.
  pip-requirements: requirements.txt

# List all files/directories that should be included in the app. Globbing
# (e.g.: configs/*.json) is supported.
files:
  - main.py
  # If you have a Gurobi license, uncomment the following line and make sure to
  # store your license information in that file.
  # - gurobi.lic

configuration:
  # Specify the format the app reads and writes.
  content:
    format: json # Read JSON from stdin and write JSON to stdout.
  # Define the options (parameters) of the app.
  options:
    strict: false
    items:
      - name: TimeLimit
        option_type: float
        default: 30.0
        description: Maximum time in seconds to spend solving
        required: false
        additional_attributes:
          min: 1.0
          max: 3600.0
          step: 1.0
        ui:
          control_type: slider
          display_name: Time Limit
      - name: MIPGap
        option_type: float
        default: 0.0001
        description: Relative MIP optimality gap
        required: false
        additional_attributes:
          min: 0.0
          max: 1.0
          step: 0.0001
        ui:
          control_type: slider
          display_name: MIP Gap
      - name: LogToConsole
        option_type: int
        default: 1
        description: Control console logging (0=off, 1=on)
        required: false
        additional_attributes:
          min: 0
          max: 1
          step: 1
        ui:
          control_type: slider
          display_name: Log To Console
