apps:
  - name: go-hello-world
    type: go
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Get started with Go and Nextmv.
  - name: go-highs-knapsack
    type: go
    app_id: knapsack-gosdk
    marketplace_app_id: knapsack.gosdk
    marketplace_major_version: v1
    description: Use Go and HiGHS - knapsack.
  - name: go-highs-orderfulfillment
    type: go
    app_id: order-fulfill-gosdk
    marketplace_app_id: order.fulfill.gosdk
    marketplace_major_version: v1
    description: Use Go and HiGHS - order fulfillment.
  - name: go-highs-shiftscheduling
    type: go
    app_id: shift-scheduling
    marketplace_app_id: shift.scheduling
    marketplace_major_version: v1
    description: Use Go and HiGHS - shift scheduling.
  - name: go-nextroute
    type: go
    app_id: nextroute
    marketplace_app_id: nextroute
    marketplace_major_version: v1
    description: Use Go and Nextroute - VRP.
  - name: java-hello-world
    type: java
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Get started with Java and Nextmv.
  - name: java-gurobi-knapsack
    type: java
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Java and Gurobi - knapsack.
  - name: java-gurobi-multiknapsack-multiexcel
    type: java
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Java and Gurobi - multi knapsack via Excel.
  - name: java-hexaly-knapsack
    type: java
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Java and Hexaly - knapsack.
  - name: java-ortools-knapsack
    type: java
    app_id: knapsack-jortools
    marketplace_app_id: knapsack.jortools
    marketplace_major_version: v1
    description: Use Java and OR-Tools - knapsack.
  - name: java-ortools-routing
    type: java
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Java and OR-Tools - VRP.
  - name: python-ampl-facilitylocation
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Python and AMPL - facility location.
  - name: python-ampl-knapsack
    type: python
    app_id: knapsack-ampl
    marketplace_app_id: knapsack.ampl
    marketplace_major_version: v1
    description: Use Python and AMPL - knapsack.
  - name: python-ampl-priceoptimization
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Python and AMPL - price optimization.
  - name: python-cuopt-routing
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Python and cuOpt - VRP.
  - name: python-gurobi-knapsack
    type: python
    app_id: knapsack-gurobi
    marketplace_app_id: knapsack.gurobi
    marketplace_major_version: v1
    description: Use Python and Gurobi - knapsack.
  - name: python-hello-world
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Get started with Python and Nextmv.
  - name: python-hexaly-generic
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Python and Hexaly - hxm models.
  - name: python-hexaly-knapsack
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Python and Hexaly - knapsack.
  - name: python-highs-knapsack
    type: python
    app_id: knapsack-highs
    marketplace_app_id: knapsack.highs
    marketplace_major_version: v1
    description: Use Python and HiGHS - knapsack.
  - name: python-nextmv-gurobipy-knapsack
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use the Python Nextmv & gurobipy integration - knapsack.
  - name: python-nextmv-scikit-learn-diabetes
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use the Python Nextmv & scikit-learn integration - diabetes.
  - name: python-gams-cutstock
    type: python
    app_id: cutstock-gams
    marketplace_app_id: cutstock.gams
    marketplace_major_version: v1
    description: Use Python and GAMS - cutstock.
  - name: python-gamspy-traveling-salesman
    type: python
    app_id: tsp-gams
    marketplace_app_id: tsp.gams
    marketplace_major_version: v1
    description: Use Python and Gamspy - traveling salesman.
  - name: python-gurobi-price-optimization
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use a Nextmvified Gurobi notebook for price optimization.
  - name: python-nextroute
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Python and Nextroute - VRP.
  - name: python-ortools-costflow
    type: python
    app_id: cost-flow-ortools
    marketplace_app_id: cost.flow.ortools
    marketplace_major_version: v1
    description: Use Python and OR-Tools - cost flow.
  - name: python-ortools-demandforecasting
    type: python
    app_id: demand-forecasting-ortools
    marketplace_app_id: dem.forecast.ortools
    marketplace_major_version: v1
    description: Use Python and OR-Tools - demand forecasting.
  - name: python-ortools-knapsack
    type: python
    app_id: knapsack-ortools
    marketplace_app_id: knapsack.ortools
    marketplace_major_version: v1
    description: Use Python and OR-Tools - knapsack.
  - name: python-ortools-knapsack-multicsv
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Python and OR-Tools - multi CSV knapsack.
  - name: python-ortools-multiknapsack-multiexcel
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Python and OR-Tools - multi knapsack via Excel.
  - name: python-ortools-region-allocation
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Python and OR-Tools - region allocation.
  - name: python-ortools-routing
    type: python
    app_id: routing-ortools
    marketplace_app_id: routing.ortools
    marketplace_major_version: v1
    description: Use Python and OR-Tools - VRP.
  - name: python-ortools-shiftassignment
    type: python
    app_id: shift-assign-ortools
    marketplace_app_id: shift.assign.ortools
    marketplace_major_version: v1
    description: Use Python and OR-Tools - shift assignment.
  - name: python-ortools-shiftplanning
    type: python
    app_id: shift-plan-ortools
    marketplace_app_id: shift.plan.ortools
    marketplace_major_version: v1
    description: Use Python and OR-Tools - shift planning.
  - name: python-pyomo-knapsack
    type: python
    app_id: knapsack-pyomo
    marketplace_app_id: knapsack.pyomo
    marketplace_major_version: v1
    description: Use Python and Pyomo - knapsack.
  - name: python-pyomo-shiftassignment
    type: python
    app_id: shift-assign-pyomo
    marketplace_app_id: shift.assign.pyomo
    marketplace_major_version: v1
    description: Use Python and Pyomo - shift assignment.
  - name: python-pyomo-shiftplanning
    type: python
    app_id: shift-plan-pyomo
    marketplace_app_id: shift.plan.pyomo
    marketplace_major_version: v1
    description: Use Python and Pyomo - shift planning.
  - name: python-pyoptinterface-knapsack
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Python and PyOptInterface - knapsack.
  - name: python-pyvroom-routing
    type: python
    app_id: routing-pyvroom
    marketplace_app_id: routing.pyvroom
    marketplace_major_version: v1
    description: Use Python and Pyvroom - VRP.
  - name: python-scip-knapsack
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Python and SCIP - knapsack.
  - name: python-tr-ortools-region-allocation
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use tracked runs in Python - region allocation.
  - name: python-vroom-premium-api-routing
    type: python
    app_id: routing-vroom-premium-api
    marketplace_app_id: routing.vroom.premium.api
    marketplace_major_version: v1
    description: Use Python and Vroom Premium API - VRP.
  - name: python-wf-custom-visuals
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use workflows in Python - custom visuals.
  - name: python-wf-ortools-region-allocation
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use workflows in Python - region allocation.
  - name: python-xpress-knapsack
    type: python
    app_id:
    marketplace_app_id:
    marketplace_major_version:
    description: Use Python and Xpress - knapsack.

# Main supported language versions.
language-support:
  go:
    version: 1.22
  python:
    version: 3.11
  java:
    version: 21
    distribution: temurin
