# This manifest holds the information the app needs to run on the Nextmv Cloud.
type: python
runtime: ghcr.io/nextmv-io/runtime/python:3.11
python:
  # All listed packages will get bundled with the app.
  pip-requirements: pyproject.toml # Can be a requirements.txt

# List all files/directories that should be included in the app. Globbing
# (e.g.: configs/*.json) is supported.
files:
  - main.py
  - floc_bend.mod
  - floc_bend.run
  # If you have an AMPL license, uncomment the following line and make sure to
  # store your license information in that file.
  # - ampl_license_uuid

configuration:
  # Specify the format the app reads and writes.
  content:
    format: json # Read JSON from stdin and write JSON to stdout.
  # Define the options (parameters) of the app.
  options:
    strict: false
    items:
      - name: duration
        option_type: int
        default: 30
        description: Max runtime duration (in seconds).
        required: false
        additional_attributes:
          min: 1
          max: 3600
          step: 10
        ui:
          control_type: slider
          display_name: Duration
      - name: provider
        option_type: string
        default: highs
        description: Solver provider.
        required: false
        ui:
          control_type: input
          display_name: Provider
      - name: runpath
        option_type: string
        default: .
        description: Path to the directory with the run file.
        required: false
        ui:
          control_type: input
          display_name: Run Path
      - name: modelpath
        option_type: string
        default: .
        description: Path to the directory with the model file.
        required: false
        ui:
          control_type: input
          display_name: Model Path
