[project]
name = "python-ampl-facilitylocation"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "ampl-module-base==20241203",
    "ampl-module-cbc==20250206",
    "ampl-module-copt==20241228",
    "ampl-module-gcg==20240724",
    "ampl-module-gecode==20220504",
    "ampl-module-gokestrel==20211022",
    "ampl-module-gurobi==20250204",
    "ampl-module-highs==20241119",
    "ampl-module-lgo==20190908",
    "ampl-module-open==20250206",
    "ampl-module-scip==20240724",
    "ampl-module-xpress==20241227",
    "amplpy==0.14.0",
    "ampltools==0.7.5",
    "nextmv==1.7.2",
    "pandas==2.2.2",
]

[[tool.uv.index]]
name = "ampl"
url = "https://pypi.ampl.com"
default = true

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
