# This manifest holds the information the app needs to run on the Nextmv Cloud.
type: python
runtime: ghcr.io/nextmv-io/runtime/python:3.11
python:
  # All listed packages will get bundled with the app.
  pip-requirements: requirements.txt

# List all files/directories that should be included in the app. Globbing
# (e.g.: configs/*.json) is supported.
files:
  - main.py
  - visuals.py

configuration:
  options:
    strict: false
    validation:
      enforce: none
    items:
      - name: input
        option_type: string
        default: ""
        required: false
        description: Path to input file. Default is stdin.
        local_only: true
      - name: output
        option_type: string
        default: ""
        required: false
        description: Path to output file. Default is stdout.
        local_only: true
      - name: objective
        option_type: string
        default: average_distance
        required: false
        description: Minimizes for average_distance, total_distance, or max_distance
        additional_attributes:
          values:
            - average_distance
            - total_distance
            - max_distance
        ui:
          control_type: select
          hidden_from:
            - operator
          display_name: Objective
      - name: parks_override
        option_type: int
        required: false
        description: Number of parks to build (from 1 to 10). Defaults to the value in the input.
        additional_attributes:
          min: 1
          max: 10
          step: 1
        ui:
          control_type: input
          hidden_from:
            - operator
          display_name: Number of parks (override)
