name: markdown lint
on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  community-apps-markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          globs: "**/*.md"
