name: python lint
on:
  push:
    branches: [develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  community-apps-python-lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: ""
    steps:
      - name: git clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: set Python version
        run: |
          export PYTHON_VERSION=$(yq '.language-support.python.version' workflow-configuration.yml)
          echo "This is the Python version => $PYTHON_VERSION"
          echo "PYTHON_VERSION=${PYTHON_VERSION}" >> $GITHUB_ENV
        working-directory: .nextmv/

      - name: install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.9.29"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install dependencies
        run: uv add ruff

      - name: lint with ruff
        run: uv run ruff check --output-format=github .
